// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9FW0cFYVuhn5K4RXtVWFrvgTWPuN3iJA',
    appId: '1:599326275912:web:b5d5b1816dd10ab1625b7d',
    messagingSenderId: '599326275912',
    projectId: 'gdsc-sollition-project',
    authDomain: 'gdsc-sollition-project.firebaseapp.com',
    storageBucket: 'gdsc-sollition-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC42x7lH452jrxxhHTK0diww11eLbj--SE',
    appId: '1:599326275912:android:4e9af8752ceca812625b7d',
    messagingSenderId: '599326275912',
    projectId: 'gdsc-sollition-project',
    storageBucket: 'gdsc-sollition-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1KYeyN9_YjCxK66Q_y1UM4EJdRBDb9KA',
    appId: '1:599326275912:ios:abe23ea87642984e625b7d',
    messagingSenderId: '599326275912',
    projectId: 'gdsc-sollition-project',
    storageBucket: 'gdsc-sollition-project.appspot.com',
    iosBundleId: 'com.example.gdscSollitionProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1KYeyN9_YjCxK66Q_y1UM4EJdRBDb9KA',
    appId: '1:599326275912:ios:73cb698d36779b3c625b7d',
    messagingSenderId: '599326275912',
    projectId: 'gdsc-sollition-project',
    storageBucket: 'gdsc-sollition-project.appspot.com',
    iosBundleId: 'com.example.gdscSollitionProject.RunnerTests',
  );
}
